BASE: ['']

TRAIN:
  EPOCHS: 500
  BATCH_SIZE: 32
  LR: 0.009
  WEIGHT_DECAY: 0.0
  SCHEDULER: 'cosine'
  CONTINUE_TRAINING: False
TEST:
  BATCH_SIZE: 32
  MODEL_PATH: ''
  FLAG: False
# Dataset
DATA:
  DATASET: 'Xinchuan'
  ROOT: 'F:\Dataset\rppg\XinChuan\stmap\meta_data\RPPG' 
  SPLIT: 0.8
FS: 25

# Model
MODEL:
  NAME: 'resnet18'
  PRETRAINED: ''
  SAVEPATH: 'G:\stmap_rsp_checkpoints'
  SAVE_INTERVAL: 10
  MODEL_PATH: ''
