BASE: ['']

TRAIN:
  EPOCHS: 500
  BATCH_SIZE: 32
  LR: 0.009
  WEIGHT_DECAY: 0.0
  SCHEDULER: 'cosine'
  PRETRAIN: False # MAE pretrain
  CONTINUE_TRAINING: False
  ENCODER_FREEZE: False

# Dataset
DATA:
  DATASET: 'Xinchuan'
  ROOT: 'F:\Dataset\rppg\XinChuan\stmap\meta_data\RPPG' 
  SPLIT: 0.8
FS: 25

# Model
MODEL:
  NAME: 'ft_vit_base_patch16'
  PRETRAINED: 'G:\stmap_rsp_checkpoints\ft_mae90_44_vit_base_patch16_202512151658\best_checkpoints\ft_vit_base_patch16_best.pth'
  SAVEPATH: 'G:\stmap_rsp_checkpoints'
  SAVE_INTERVAL: 50
  MODEL_PATH: ''


